### ISSUE TITLE
Changing to element breaks test

### ISSUE THREAD

**Issue by bootstraponline** [cheezy/page-object#278]
If I use the button method in a page object, the test passes.

```ruby
button 'my_button',   css: 'some css' # works
```

If I change to the element method in the page object, the test breaks.

```ruby
element 'my_button',   css: 'some css' # breaks
```

```
     Failure/Error: my_page.my_button
     Selenium::WebDriver::Error::InvalidSelectorError:
       The given selector (.//{:css=>"#my css"})[1] is either invalid or does not result in a WebElement. The following error occurred:
       InvalidSelectorError: Unable to locate an element with the xpath expression (.//{:css=>"#my css"})[1] because of the following error:
       SyntaxError: The expression is not a legal expression.
     # [remote server] file:///var/folders/w7/c1yh5bps5dnc0frz0tbj_dmh0000gn/T/webdriver-profile20150423-50132-edkpx2/extensions/fxdriver@googlecode.com/components/driver-component.js:10245:in `FirefoxDriver.annotateInvalidSelectorError_'
     # [remote server] file:///var/folders/w7/c1yh5bps5dnc0frz0tbj_dmh0000gn/T/webdriver-profile20150423-50132-edkpx2/extensions/fxdriver@googlecode.com/components/driver-component.js:10276:in `FirefoxDriver.prototype.findElementInternal_'
     # [remote server] file:///var/folders/w7/c1yh5bps5dnc0frz0tbj_dmh0000gn/T/webdriver-profile20150423-50132-edkpx2/extensions/fxdriver@googlecode.com/components/driver-component.js:10280:in `FirefoxDriver.prototype.findElement'
     # [remote server] file:///var/folders/w7/c1yh5bps5dnc0frz0tbj_dmh0000gn/T/webdriver-profile20150423-50132-edkpx2/extensions/fxdriver@googlecode.com/components/command-processor.js:12274:in `DelayedCommand.prototype.executeInternal_/h'
     # [remote server] file:///var/folders/w7/c1yh5bps5dnc0frz0tbj_dmh0000gn/T/webdriver-profile20150423-50132-edkpx2/extensions/fxdriver@googlecode.com/components/command-processor.js:12279:in `DelayedCommand.prototype.executeInternal_'
     # [remote server] file:///var/folders/w7/c1yh5bps5dnc0frz0tbj_dmh0000gn/T/webdriver-profile20150423-50132-edkpx2/extensions/fxdriver@googlecode.com/components/command-processor.js:12221:in `DelayedCommand.prototype.execute/<'
     # /Users/user/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/response.rb:52:in `assert_ok'
     # /Users/user/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/response.rb:15:in `initialize'
     # /Users/user/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/http/common.rb:59:in `new'
     # /Users/user/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/http/common.rb:59:in `create_response'
     # /Users/user/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/http/default.rb:66:in `request'
     # /Users/user/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
     # /Users/user/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/bridge.rb:640:in `raw_execute'
     # /Users/user/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/bridge.rb:618:in `execute'
     # /Users/user/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/remote/bridge.rb:586:in `find_element_by'
     # /Users/user/.rvm/gems/ruby-2.1.5/gems/selenium-webdriver-2.45.0/lib/selenium/webdriver/common/search_context.rb:42:in `find_element'
     # /Users/user/.rvm/gems/ruby-2.1.5/gems/page-object-1.0.3/lib/page-object/platforms/selenium_webdriver/page_object.rb:1047:in `find_selenium_element'
     # /Users/user/.rvm/gems/ruby-2.1.5/gems/page-object-1.0.3/lib/page-object/platforms/selenium_webdriver/page_object.rb:980:in `element_for'
     # /Users/user/.rvm/gems/ruby-2.1.5/gems/page-object-1.0.3/lib/page-object/accessors.rb:1198:in `block in element'
     # /Users/user/.rvm/gems/ruby-2.1.5/gems/page-object-1.0.3/lib/page-object/accessors.rb:1194:in `block in element'
```

Is element not meant to be used?

**Comment by daneandersen** [comment]
The method element takes an extra parameter of the element type. so 

`button 'my_button',   css: 'some css'`

becomes

`element 'my_button',   :button, css: 'some css'`

or if the element type doesn't matter:

`element 'my_button',  :element, css: 'some css'`

**Comment by bootstraponline** [comment]
Thanks!
