### ISSUE TITLE
uninitialized constant Watir::Atoms (NameError)

### ISSUE THREAD

**Issue by bootstraponline** [cheezy/page-object#282]
I'm trying out master for the button fix and it's crashing with this error. Reverting to the last released version of page-object works.

`gem 'page-object', git: 'https://github.com/cheezy/page-object.git', ref: '9e188dbb5ab8251a6bc858c3412b3d51cb3f7544'`

```
$ bundle exec rspec
/Users/user/.rvm/gems/ruby-2.1.5/gems/watir-webdriver-0.7.0/lib/watir-webdriver/extensions/select_text.rb:1:in `<top (required)>': uninitialized constant Watir::Atoms (NameError)
  from /Users/user/.rvm/gems/ruby-2.1.5/bundler/gems/page-object-9e188dbb5ab8/lib/page-object/platforms/watir_webdriver/element.rb:1:in `require'
  from /Users/user/.rvm/gems/ruby-2.1.5/bundler/gems/page-object-9e188dbb5ab8/lib/page-object/platforms/watir_webdriver/element.rb:1:in `<top (required)>'
  from /Users/user/.rvm/gems/ruby-2.1.5/bundler/gems/page-object-9e188dbb5ab8/lib/page-object.rb:12:in `require'
  from /Users/user/.rvm/gems/ruby-2.1.5/bundler/gems/page-object-9e188dbb5ab8/lib/page-object.rb:12:in `<top (required)>'
  from /Users/user/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `load'
  from /Users/user/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1226:in `block in load_spec_files'
  from /Users/user/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `each'
  from /Users/user/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/lib/rspec/core/configuration.rb:1224:in `load_spec_files'
  from /Users/user/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:97:in `setup'
  from /Users/user/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:85:in `run'
  from /Users/user/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:70:in `run'
  from /Users/user/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/lib/rspec/core/runner.rb:38:in `invoke'
  from /Users/user/.rvm/gems/ruby-2.1.5/gems/rspec-core-3.2.3/exe/rspec:4:in `<top (required)>'
  from /Users/user/.rvm/gems/ruby-2.1.5/bin/rspec:23:in `load'
  from /Users/user/.rvm/gems/ruby-2.1.5/bin/rspec:23:in `<main>'
  from /Users/user/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
  from /Users/user/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by bootstraponline** [comment]
I had to update my code like this to get the master branch running:


```ruby
# spec_helper.rb
require 'watir-webdriver/atoms'
require 'page-object'
```

before it worked without a watir require.

**Comment by daneandersen** [comment]
thanks for the input, I'll check it out.

**Comment by daneandersen** [comment]
I tracked down the reason for this and put in the code change that should fix it.

**Comment by bootstraponline** [comment]
Thank you. I confirm this fixes the issue.
