### ISSUE TITLE
Unkown exception when locating elements inside a Frame, when switching to watir 6 and new page-objet gem

### ISSUE THREAD

**Issue by Th33x1l3** [cheezy/page-object#399]
## Error message and trace:
```
Watir::Exception::UnknownObjectException: timed out after 30 seconds, waiting for {:name=>"mainFrame", :tag_name=>"frame"} --> {:id=>"user", :tag_name=>"textarea"} to be located
(eval):1:in `process_watir_call'
./lib/pages/login/index.rb:23:in `login_with'
./features/step_definitions/login_steps.rb:5:in `/^I\ login\ with\ user\ (.*)$/'
./features/Fluxogramas/Dispneia_Crianca.feature:31:in `And I login with user triador'
./features/Fluxogramas/Dispneia_Crianca.feature:6:in `And I login with user triador'

```

## Code in question:

```
require_relative('../../pages/base')
require 'rconfig'
module Pages
  class LoginPage < Pages::Base
    include PageObject
    include Utils::LocalLogger

    in_frame(:name => 'mainFrame') do |frame|

      checkbox(:use_card, :id => 'login_cartao', :frame => frame)
      text_area(:user, :id => 'user', :frame => frame)
      text_area(:pass, :id => 'pwd', :frame => frame)
      div(:shadow_pass, :id=>'mydiv', :frame=> frame)
      div(:cancel_button, :id => 'login_cancelar', :frame => frame)
      div(:login_button, :id => 'login_confirmar', :frame => frame)
      link(:change_pwd, :id => 'altera_password', :frame => frame)
      div(:error_msg, :class => 'linhaErro', :frame => frame)

    end

    def login_with(user, password)
      all_logger.debug("Trying to log in with user #{user}, pass #{password}")
      self.user=user  ### <--- line 23, file ./lib/pages/login/index.rb
      shadow_pass_element.click
      pass_element.when_visible(10).value= password

      login_button_element.click
    end
(...)

 ```

## Gems used (from gemfile lock):

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (5.0.0.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (~> 0.7)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    ansi (1.5.0)
    archive-zip (0.7.0)
      io-like (~> 0.3.0)
    awesome_print (1.7.0)
    builder (3.2.2)
    childprocess (0.5.9)
      ffi (~> 1.0, >= 1.0.11)
    chromedriver-helper (1.0.0)
      archive-zip (~> 0.7.0)
      nokogiri (~> 1.6)
    concurrent-ruby (1.0.2)
    crtu (0.2.4.3)
      cucumber (~> 2.3, > 2.3.0)
      log4r (~> 1.1, >= 1.1.10)
    cucumber (2.4.0)
      builder (>= 2.1.2)
      cucumber-core (~> 1.5.0)
      cucumber-wire (~> 0.0.1)
      diff-lcs (>= 1.1.3)
      gherkin (~> 4.0)
      multi_json (>= 1.7.5, < 2.0)
      multi_test (>= 0.1.2)
    cucumber-core (1.5.0)
      gherkin (~> 4.0)
    cucumber-wire (0.0.1)
    data_magic (0.22)
      faker (>= 1.1.2)
      yml_reader (>= 0.6)
    diff-lcs (1.2.5)
    faker (1.6.6)
      i18n (~> 0.5)
    ffi (1.9.14)
    gherkin (4.0.0)
    headless (2.3.1)
    i18n (0.7.0)
    io-like (0.3.0)
    json (2.0.2)
    log4r (1.1.10)
    logger (1.2.8)
    mini_portile2 (2.1.0)
    minitest (5.9.1)
    minitest-reporters (1.1.12)
      ansi
      builder
      minitest (>= 5.0)
      ruby-progressbar
    multi_json (1.12.1)
    multi_test (0.1.2)
    net-http-persistent (2.9.4)
    nokogiri (1.6.8.1)
      mini_portile2 (~> 2.1.0)
    page_navigation (0.10)
      data_magic (>= 0.22)
    rake (11.3.0)
    require_all (1.3.3)
    rspec (3.5.0)
      rspec-core (~> 3.5.0)
      rspec-expectations (~> 3.5.0)
      rspec-mocks (~> 3.5.0)
    rspec-core (3.5.4)
      rspec-support (~> 3.5.0)
    rspec-expectations (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-mocks (3.5.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.5.0)
    rspec-support (3.5.0)
    ruby-progressbar (1.8.1)
    rubyzip (1.2.0)
    selenium-webdriver (3.0.1)
      childprocess (~> 0.5)
      rubyzip (~> 1.0)
      websocket (~> 1.0)
    thread_safe (0.3.5)
    to_regexp (0.2.1)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    watir (6.0.2)
      selenium-webdriver (~> 3.0)
    websocket (1.2.3)
    yard (0.9.5)
    yml_reader (0.7)

```

## Description

After updating gems via bundle update, and making the necessary correction in requires, the cucumber tests hangs when trying to input the login/password. Tested both with firefox and chrome, in a no headless case (headless also give the same error).
Test hangs about 30 seconds and then errors out.

**Comment by cheezy** [comment]
Can you tell me what version of page-object you are using?  It is not listed in the Gemfile.lock file for some reason.

**Comment by Th33x1l3** [comment]
Ah, it's because i'm building it from source, aka your repo.

 gem 'page-object', :git=>'https://github.com/cheezy/page-object'

**Comment by cheezy** [comment]
Can you confirm that the name field is indeed a textarea?

**Comment by Th33x1l3** [comment]
i changed to textfield method, and it passed. Change in watir API?

**Comment by cheezy** [comment]
I think so.  There was an entry in the changelog for 6.0.0 stating:

Element#text_field no longer locates textareas - use Element#textarea instead.


It is possible that they also tightened textarea to not find text_field.

**Comment by Th33x1l3** [comment]
Ok closing it. Changing from textarea to textfield worked. Maybe putting a warning in page readme because watir 6 api changes, so no more tickets like this?

**Comment by Th33x1l3** [comment]
@cheezy maybe you can put a warning on site Readme or gem installation that watir 6 restricted the scope on element finding. It's a pretty big change

**Comment by titusfortner** [comment]
What changed recently should have been throwing a deprecation warning every time it was used for the past 2 years.

**Comment by Th33x1l3** [comment]
in a ideal world, this would happen. I can bet that this change was something like one developer seeing a unusual behavior and thought that it was a quick fix, with low impact. Changed it both ways, recorded in changelog one-way (text_field-> textarea) and done.

Well, now i revised the code and checked each field if it was really a text area or text field and changed accordingly, and it works.

In the end, it is a very valid change, but it can and should be documented fully and with a warning in gem update (at least) so people can be wary of it, and change code accordingly.
