### ISSUE TITLE
PageObject.register_widget undefined method

### ISSUE THREAD

**Issue by tjonesmi** [cheezy/page-object#446]
I seem to be missing something on adding a widget. 
I get the following error calling a widget named "group"

```
  Scenario: Login with valid id
    Given I am on the login page
    And I have entered valid credentials
      undefined method `group' for #<Watir::Browser:0x007fc12ebb78c0> (NoMethodError)
      ./features/step_definitions/login-steps.rb:10:in `block (2 levels) in <top (required)>'
      ./features/step_definitions/login-steps.rb:8:in `/^I have entered valid credentials$/'
      features/login.feature:5:in `And I have entered valid credentials'
```

ChoseSelect.rb
---------------
```ruby
class ChosenSelect < PageObject::Elements::TextField
    def self.hello(msg) 
      puts msg
    end
end
```

env.rb
------
```ruby
equire 'rspec'
require 'selenium-webdriver'
require 'page-object'
require 'page-object/page_factory'

# Initialize PageObjects
World(PageObject::PageFactory)

# Load all the Page objects
require_relative './page-object/ChosenSelect'
PageObject.register_widget :chosen_select, ChosenSelect, :text
Dir['./pages/**/*.rb'].each {|file| require file }
```

LoginPage.rb
-------------
```ruby
class LoginPage
	include PageObject

	page_url "#{FigNewton.url}/Traffic"

	chosen_select(:group, :xpath => "//INPUT[@ng-model='credentials.lanId']") 
	text_field(:lan_id, :xpath => "//INPUT[@ng-model='credentials.lanId']") 
	text_field(:password, :xpath => "//INPUT[@ng-model='credentials.password']") 
	button(:login, :xpath => "//BUTTON[normalize-space(text())='login']") 
	div(:alert, :css => "div.alert")
end
```

login-steps.rb
--------------
```ruby
Given /^I have entered valid credentials$/ do 
  on_page(LoginPage) do | page |
    page.populate_page_with data_for "LoginPage/valid"
    page.group.hello('jdjdj')
    page.login
  end
end
````

**Comment by jkotests** [comment]
The method created by the accessor will be `#group_element` rather than `#group`, so you want:

~~~~~~~~ruby
page.group_element.hello('jdjdj')
~~~~~~~~

**Comment by tjonesmi** [comment]
Thanks for your response.  I created a standalone GEM and called the group_element.hello and that worked.
