### ISSUE TITLE
unable to run page-object using selenium 4 beta

### ISSUE THREAD

**Issue by anilreddy** [cheezy/page-object#502]
While am running page-object using selenium 4 beta am getting following error.

```ruby
C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/specification.rb:2241:in `raise_if_conflicts': Unable to activate page-object-2.2.6, because selenium-webdriver-4.0.0.beta2 conflicts with selenium-webdriver (~> 3.0) (Gem::ConflictError)        from C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/specification.rb:1364:in `activate'
        from C:/Ruby30-x64/lib/ruby/3.0.0/rubygems.rb:221:in `rescue in try_activate'
        from C:/Ruby30-x64/lib/ruby/3.0.0/rubygems.rb:214:in `try_activate'
        from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:153:in `rescue in require'
        from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from E:/Anil/Watir/table_page.rb:2:in `<top (required)>'
        from ./table.rb:1:in `require_relative'
        from ./table.rb:1:in `<main>'
C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/specification.rb:2241:in `raise_if_conflicts': Unable to activate page-object-2.2.6, because selenium-webdriver-4.0.0.beta2 conflicts with selenium-webdriver (~> 3.0) (Gem::ConflictError)        from C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/specification.rb:1364:in `activate'
        from C:/Ruby30-x64/lib/ruby/3.0.0/rubygems.rb:215:in `try_activate'
        from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:153:in `rescue in require'
        from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from E:/Anil/Watir/table_page.rb:2:in `<top (required)>'
        from ./table.rb:1:in `require_relative'
        from ./table.rb:1:in `<main>'
<internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- page-object (LoadError)
        from <internal:C:/Ruby30-x64/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from E:/Anil/Watir/table_page.rb:2:in `<top (required)>'
        from ./table.rb:1:in `require_relative'
        from ./table.rb:1:in `<main>'
```

**Comment by jkotests** [comment]
The restriction on the Selenium version has been removed in v2.3.1. Note that you'll also want to get Watir 7.0.0.beta1, which supports Selenium 4.
